### ISSUE TITLE
Auto-value test failure on Apple JVM 1.6 on a mac.

### ISSUE THREAD

**Issue by cgruber** [google/auto#109]
The CompilationTest fails on mac's 1.6 java virtual machine.  It's unclear why, but it seems like it's building an invalid AutoValue_Baz lacking a return type, though I suspect that is a masking error.

Commit (though I had to bump pom version numbers too, so this failure is only seen when ref 85939616c50f3eed8f347b7ec743497b03c7ae3a is applied and the build proceeds to run this test:

```
commit 46146a1f30e8ef8825ea1aaa33924e7aa1b41d5d
Author:     Éamonn McManus <eamonn@mcmanus.net>
AuthorDate: Tue Jun 17 18:39:10 2014 -0700
Commit:     Christian Edward Gruber <cgruber@google.com>
CommitDate: Wed Jun 18 01:49:17 2014 -0700

    Add a test to AutoValue's CompilationTest that uses compile-testing's generatesSources clause to check that the generated co~
    -------------
    Created by MOE: http://code.google.com/p/moe-java
    MOE_MIGRATED_REVID=68848125
```

Here's the failure.  This is all done in memory, so 
```
testCompilation(com.google.auto.value.processor.CompilationTest)  Time elapsed: 0.074 sec  <<< ERROR!
java.lang.IllegalStateException: error while parsing:
foo/bar/AutoValue_Baz.java:7: invalid method declaration; return type required

        at com.google.testing.compile.Compilation.parse(Compilation.java:100)
        at com.google.testing.compile.JavaSourcesSubject$SuccessfulCompilationBuilder.generatesSources(JavaSourcesSubject.java:261)
        at com.google.auto.value.processor.CompilationTest.testCompilation(CompilationTest.java:99)
```

**Comment by eamonnmcmanus** [comment]
This was fixed internally on 18 June 2014 but I forgot to close the external issue.
