### ISSUE TITLE
autovalue fails when runnning `mvn verify`

### ISSUE THREAD

**Issue by jmcampanini** [google/auto#125]
when running `mvn verify` from the `auto/value` project gives this:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.google.auto.value.processor.AbstractMethodExtractorTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.114 sec
Running com.google.auto.value.processor.AbstractMethodListerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 sec
Running com.google.auto.value.processor.CompilationErrorsTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.052 sec
Running com.google.auto.value.processor.CompilationTest
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.636 sec
Running com.google.auto.value.processor.JavaTokenizerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running com.google.auto.value.processor.TemplateVarsTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running com.google.auto.value.processor.TypeSimplifierTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.071 sec <<< FAILURE!
testTypeSimplifierErrorTypes(com.google.auto.value.processor.TypeSimplifierTest)  Time elapsed: 0.024 sec  <<< FAILURE!
junit.framework.AssertionFailedError: [/var/folders/jk/0ylhts1j1szcnnf7pnr1wykm0000gn/T/1408099842353-0/ExtendsUndefinedType.java:1: error: cannot find symbol
public class ExtendsUndefinedType extends MissingType {}
                                          ^
  symbol: class MissingType, /var/folders/jk/0ylhts1j1szcnnf7pnr1wykm0000gn/T/1408099842353-0/ExtendsUndefinedType.java:1: error: cannot find symbol
public class ExtendsUndefinedType extends MissingType {}
                                          ^
  symbol: class MissingType] expected:<[]> but was:<[/var/folders/jk/0ylhts1j1szcnnf7pnr1wykm0000gn/T/1408099842353-0/ExtendsUndefinedType.java:1: error: cannot find symbol
public class ExtendsUndefinedType extends MissingType {}
                                          ^
  symbol: class MissingType]>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.TestCase.assertEquals(TestCase.java:244)
	at com.google.auto.value.processor.TypeSimplifierTest.doTestTypeSimplifier(TypeSimplifierTest.java:170)
	at com.google.auto.value.processor.TypeSimplifierTest.doTestTypeSimplifierWithSources(TypeSimplifierTest.java:111)
	at com.google.auto.value.processor.TypeSimplifierTest.testTypeSimplifierErrorTypes(TypeSimplifierTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running com.google.auto.value.processor.VelocityClassLoaderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.278 sec
```

this is building on commit hash: `23a8e52`

this also fails if you run from the root project: `mvn -f build-pom.xml verify`

**Comment by eamonnmcmanus** [comment]
Assuming this is no longer relevant. Please reopen if I am wrong.
