### ISSUE TITLE
AutoService should verify presence of a no-argument public constructor

### ISSUE THREAD

**Issue by vlsi** [google/auto#1505]
Here's a stacktrace when `ServiceLoader` fails to find a constructor in runtime.

It would be nice if `@AutoService` could capture that at the compile-time.

Then, it would be nice to check that `@AutoService` class is not abstract, and it should not be an interface either.

```
org.apache.jmeter.functions.Function: org.apache.jmeter.functions.Groovy Unable to get public no-arg constructor
java.util.ServiceConfigurationError: org.apache.jmeter.functions.Function: org.apache.jmeter.functions.Groovy Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1491)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.apache.jmeter.functions.FunctionServicesTest.__counter loads(FunctionServicesTest.kt:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:45)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:146)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:146)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NoSuchMethodException: org.apache.jmeter.functions.Groovy.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	... 66 more
```

**Comment by eamonnmcmanus** [comment]
I think that's the TODO [here](https://github.com/google/auto/blob/0e6bbe20e2ea77e22d775de528a6bae2cf433813/service/processor/src/main/java/com/google/auto/service/processor/AutoServiceProcessor.java#L236-L237). It does seem like something we could do pretty easly.

**Comment by eamonnmcmanus** [comment]
After looking into this, I find that within Google's source base there are many classes that use `@AutoService` but don't have public no-arg constructors. Typically it's because they're using a framework that looks for `META-INF/services` entries, but doesn't use `ServiceLocator`. For instance the framework might perform injection on the classes it finds. Robolectric does this, for example. So I think requiring a public no-arg constructor probably won't work.

I do think there are some changes we can make:

* Invert the inexplicable default of only checking that the class does implement its `@AutoService` interface if compiled with `-Averify=true`.
* Reject `@AutoService` on interfaces and abstract classes.
* Allow `@SuppressWarnings("AutoService")` to disable these checks and the existing must-implement-the-interface one, rather than having to compile with `-Averify=false`.

**Comment by vlsi** [comment]
> Typically it's because they're using a framework that looks for META-INF/services entries, but doesn't use ServiceLocator.

Oh, that is an interesting idea.
I'm trying to add `@AutoService` + `ServiceLocator` to Apache JMeter instead of the existing "find class files on the classpath": https://github.com/apache/jmeter/pull/5885.
The fact that `ServiceLoader` instantiates all services it finds does bite me.

By the way, there might be several verify keys like:
* `autoServiceVerifyInstanceOf` (== the current `verify`)
* `autoServiceVerifyNonAbstract`
* `autoServiceVerifyDefaultConstructor`
* `autoServiceVerifyForServiceLoader` (== `autoServiceVerifyInstanceOf` + `autoServiceVerifyNonAbstract` + `autoServiceVerifyDefaultConstructor`)

WDYT?

**Comment by eamonnmcmanus** [comment]
I think having several flavours of `@SuppressWarnings` might be overkill. But perhaps we could have `@AutoService(value = MyService.class, forServiceLoader = true)` for when you definitely _are_ using `ServiceLoader`. Then we could check that your class is public and has a public no-arg constructor.

**Comment by tbroyer** [comment]
I'd rather do `forServiceLoader=false` (i.e. have it as `true` by default, allow disabling it for those cases like Robolectric)

**Comment by vlsi** [comment]
I do not suggest several `@SuppressWarnings`. I just thought there might be several properties so the users could select the verifications they need.

For instance, it looks like `autoservice` verifies nothing by default, and the users have to opt-in by adding `-Averify=true`.

---

> allow disabling it for those cases like Robolectric

It looks like that the only backward compatible change would be when the new checks are **disabled** by default since they would break Robolectric-like cases.

In that sense, `verify` becomes a too broad setting, as it would be hard to tell what does it really verify.

So WDYT of keeping `verify` as it was before for backward compatibility, and adding new properties that either enable individual checks or enable sets of checks (e.g. all checks that are required for `ServiceLoader`)?

**Comment by eamonnmcmanus** [comment]
I think `-A` options are usually a poor idea, and I'm not in favour of having _more_ of them. I'd even love to get rid of `-Averify`, especially since it also has such a global name: who knows what other things besides AutoService are controlled by `-Averify`? I think code should be understandable by reading it where it is, without having to go and look in some completely different place to figure out what options it might have been compiled with. I also incidentally think `javac -parameters` is a poor idea too, for the same reason.

If I were designing AutoService from scratch, I would have it do all the ServiceLoader checks by default, with a way to disable some or all of them. However, we have a lot of existing users. There are thousands in Google's internal source base alone, dozens of which would need to have those checks disabled. So I think defaulting to `forServiceLoader=true` is unfortunately not viable.

It's worth remembering that doing these extra checks means discovering at compile time something that you would otherwise have discovered at run time. If we miss doing the checks, it's just a minor annoyance for the developer. Having to write `forServiceLoader=true` is also a minor annoyance, and maybe it's better to do nothing beyond the three things I mentioned in my [earlier comment](https://github.com/google/auto/issues/1505#issuecomment-1542429631).

**Comment by eamonnmcmanus** [comment]
At this stage I think we've done everything we're going to do here.
