### ISSUE TITLE
AutoValue: Crash with seemingly normal code

### ISSUE THREAD

**Issue by kenzierocks** [google/auto#200]
I made a small change in some code recently and it caused the crash below. The subset of the project that caused the crash is available on https://github.com/TechShroom/Slithering-Latte/tree/showbug/av-crash. The specific change is https://github.com/TechShroom/Slithering-Latte/commit/c3dbdc1b13956314860b22e272067378efb67feb

```
@AutoValue processor threw an exception: java.lang.IllegalArgumentException
	at autovalue.shaded.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at autovalue.shaded.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at autovalue.shaded.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.google.auto.value.processor.AbstractMethodLister.abstractNoArgMethodsX(AbstractMethodLister.java:50)
	at com.google.auto.value.processor.AbstractMethodLister.abstractNoArgMethods(AbstractMethodLister.java:43)
	at com.google.auto.value.processor.EclipseHack$BinaryPropertyOrderer.determinePropertyOrder(EclipseHack.java:240)
	at com.google.auto.value.processor.EclipseHack.reorderProperties(EclipseHack.java:98)
	at com.google.auto.value.processor.EclipseHack.reorderProperties(EclipseHack.java:86)
	at com.google.auto.value.processor.AutoValueProcessor.defineVarsForType(AutoValueProcessor.java:424)
	at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:369)
	at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:127)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:110)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:851)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:432)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:367)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.compile(IncrementalImageBuilder.java:330)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:304)
	at org.eclipse.jdt.internal.core.builder.IncrementalImageBuilder.build(IncrementalImageBuilder.java:135)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildDeltas(JavaBuilder.java:267)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:195)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:730)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:298)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:301)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:357)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:380)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:239)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

```

**Comment by kenzierocks** [comment]
Must have been an Eclipse thing, it seems to have disappeared after a few restarts.

**Comment by eamonnmcmanus** [comment]
Thanks for the report, anyway! The code in question is trying to work around a bug in Eclipse. That bug has been fixed, and as soon as the fix is present in mainstream Eclipse we will try to find a way to detect that the fix is present, and not invoke the workaround in that case. The fact that you encountered another bug in Eclipse motivates us to do this because it means that the workaround is not completely harmless.

**Comment by kenzierocks** [comment]
Ah, I happen to be running Mars right now. That makes sense. At least running clean seems to fix it.

**Comment by kenzierocks** [comment]
I'd like for the aforementioned fix to become present, as I just ran in to this error again today. As Mars has landed, I assume the fix is now in mainstream Eclipse.

**Comment by eamonnmcmanus** [comment]
I'm not sure I'll have time to figure out how to do that properly (detect Eclipse version ≥ 4.5), but a simple workaround is to change [this line](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/EclipseHack.java#L171) so it catches any Exception and not just IOException. I'll look into getting that in.
