### ISSUE TITLE
Compilation with JDK9 fails

### ISSUE THREAD

**Issue by leventov** [google/auto#334]
```
An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.NoClassDefFoundError: javax/annotation/Generated
        at com.google.auto.value.processor.AutoValueProcessor.defineVarsForType(AutoValueProcessor.java:457)
        at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:409)
        at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:143)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(jdk.compiler@9-ea/JavacProcessingEnvironment.java:958)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(jdk.compiler@9-ea/JavacProcessingEnvironment.java:874)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2100(jdk.compiler@9-ea/JavacProcessingEnvironment.java:106)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(jdk.compiler@9-ea/JavacProcessingEnvironment.java:1181)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(jdk.compiler@9-ea/JavacProcessingEnvironment.java:1289)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(jdk.compiler@9-ea/JavaCompiler.java:1229)
        at com.sun.tools.javac.main.JavaCompiler.compile(jdk.compiler@9-ea/JavaCompiler.java:903)
        at com.sun.tools.javac.main.Main.compile(jdk.compiler@9-ea/Main.java:269)
        at com.sun.tools.javac.main.Main.compile(jdk.compiler@9-ea/Main.java:144)
        at com.sun.tools.javac.Main.compile(jdk.compiler@9-ea/Main.java:55)
        at com.sun.tools.javac.Main.main(jdk.compiler@9-ea/Main.java:41)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
        at java.net.URLClassLoader.findClass(java.base@9-ea/URLClassLoader.java:384)
        at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:486)
        at java.lang.ClassLoader.loadClass(java.base@9-ea/ClassLoader.java:419)
        ... 14 more
```

**Comment by leventov** [comment]
Probably related to https://bugs.openjdk.java.net/browse/JDK-8152931

**Comment by eamonnmcmanus** [comment]
That's messy. Are you getting this from the latest snapshot of AutoValue? I would expect it to be [this line](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/processor/AutoValueProcessor.java#L607), and I think we should just use the string "javax.annotation.Generated" instead of Generated.class.getName().

**Comment by leventov** [comment]
I got this with `1.2`.

Alexey Shipilev resolved this by removing `@Generated` altogether: https://bugs.openjdk.java.net/browse/CODETOOLS-7901643 However JMH has different use scenarios and removing `@Generated` might be less reasonable for Auto projects.

**Comment by eamonnmcmanus** [comment]
I think this bug has been fixed. Please let me know if you are still seeing it.

**Comment by chajath** [comment]
I don't think this issue has been resolved. I've tried compiling a maven project on oraclejdk9 and Auto still tags classes with @javax.annotation.Generated, causing build to fail

**Comment by eamonnmcmanus** [comment]
Which version of AutoValue failed for you?

**Comment by chajath** [comment]
I'm using 1.5
https://github.com/google/guice-aqueduct/blob/master/pom.xml

**Comment by eamonnmcmanus** [comment]
The latest version is 1.5.3. Can you try with that?

**Comment by chajath** [comment]
Tried with 1.5.3 and it worked (without javax.annotation dependency). Sorry for the noise :)

**Comment by chajath** [comment]
I'd say its still problematic from a library vendor's perspective. If I publish a jar compiled on Java 8, Java 9 users would still find it troublesome without javax.annotation. The reverse would be even worse. Any recommendation as to how we can make jars that can be compatible throughout jdk7~9?

**Comment by eamonnmcmanus** [comment]
Can you explain exactly why you think it would be problematic?
