### ISSUE TITLE
Unable to create an Extension

### ISSUE THREAD

**Issue by naturalwarren** [google/auto#341]
I'm unable to make an extension. When I include the two dependencies in my build.gradle I get the build error below.

```
    compile 'com.google.auto.value:auto-value:1.2'
    compile 'com.google.auto.service:auto-service:1.0-rc2'
```

```
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.google.auto/auto-common/pom.xml
	File1: /Users/Warren1/.gradle/caches/modules-2/files-2.1/com.google.auto.value/auto-value/1.2/6873fed014fe1de1051aae2af68ba266d2934471/auto-value-1.2.jar
	File2: /Users/Warren1/.gradle/caches/modules-2/files-2.1/com.google.auto/auto-common/0.3/4073ab16ab4aceb9a217273da6442166bf51ae16/auto-common-0.3.jar

	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:57)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 68 more
Caused by: com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.google.auto/auto-common/pom.xml
	File1: /Users/Warren1/.gradle/caches/modules-2/files-2.1/com.google.auto.value/auto-value/1.2/6873fed014fe1de1051aae2af68ba266d2934471/auto-value-1.2.jar
	File2: /Users/Warren1/.gradle/caches/modules-2/files-2.1/com.google.auto/auto-common/0.3/4073ab16ab4aceb9a217273da6442166bf51ae16/auto-common-0.3.jar

	at com.android.build.gradle.internal.transforms.MergeJavaResourcesTransform.transform(MergeJavaResourcesTransform.java:302)
	at com.android.build.gradle.internal.pipeline.TransformTask$3.call(TransformTask.java:178)
	at com.android.build.gradle.internal.pipeline.TransformTask$3.call(TransformTask.java:174)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
	... 77 more
Caused by: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/maven/com.google.auto/auto-common/pom.xml
	File1: /Users/Warren1/.gradle/caches/modules-2/files-2.1/com.google.auto.value/auto-value/1.2/6873fed014fe1de1051aae2af68ba266d2934471/auto-value-1.2.jar
	File2: /Users/Warren1/.gradle/caches/modules-2/files-2.1/com.google.auto/auto-common/0.3/4073ab16ab4aceb9a217273da6442166bf51ae16/auto-common-0.3.jar
```

**Comment by naturalwarren** [comment]
I had to exclude these files. 
```
packagingOptions {
        exclude 'META-INF/maven/com.google.auto/auto-common/pom.xml'
        exclude 'META-INF/maven/com.google.auto.service/auto-service/pom.properties'
        exclude 'META-INF/maven/com.google.auto/auto-common/pom.properties'
        exclude 'META-INF/maven/com.google.guava/guava/pom.properties'
        exclude 'META-INF/maven/com.google.auto.service/auto-service/pom.xml'
        exclude 'META-INF/maven/com.google.guava/guava/pom.xml'
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
```

**Comment by JakeWharton** [comment]
Extensions should not be Android projects. Use a Java module.
