### ISSUE TITLE
Implementing an Extension Results in Error snapshot 1.3

### ISSUE THREAD

**Issue by naturalwarren** [google/auto#342]
Seeing this when creating an extension. Can anyone help discern what's wrong?

```
Caused by: java.util.ServiceConfigurationError: com.google.auto.value.extension.AutoValueExtension: Error reading configuration file
	at com.google.auto.value.processor.AutoValueProcessor.applicableExtensions(AutoValueProcessor.java:490)
	at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:422)
	at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:150)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 34 more
Caused by: java.util.zip.ZipException: invalid distance too far back
	... 45 more
```

**Comment by eamonnmcmanus** [comment]
Looks like you have a corrupt jar file. Maybe try cleaning and rebuilding.

**Comment by naturalwarren** [comment]
Didn't help. Even did a `gw clean --refresh-dependencies`

**Comment by naturalwarren** [comment]
Seemed to be an intermittent problem related to my local setup. Had a friend build my branch and it worked for him.

**Comment by naturalwarren** [comment]
I think this may be related to using Android Studio and a gradle terminal at the same time. Upon closing Android Studio the problem resolved itself.

**Comment by hzsweers** [comment]
I'm seeing this again now too, with IntelliJ. Not really sure what the deal is unless the dependency downloader in the IDE is somehow corrupting jars

**Comment by hzsweers** [comment]
Specifically, the stacktrace indicates

```
Caused by: java.io.FileNotFoundException: JAR entry META-INF/services/com.google.auto.value.extension.AutoValueExtension not found in /Users/pandanomic/dev/java/contributing/auto-value-moshi/auto-value-moshi/build/libs/auto-value-moshi-0.4.3-SNAPSHOT.jar
```

Yet when I dig into that jar, it's there. 100% reproducible on https://github.com/rharter/auto-value-moshi when running `./gradlew compileJava`

**Comment by cketcham** [comment]
I'm getting this as well. After I stop the gradle daemon it seems to work.

**Comment by eamonnmcmanus** [comment]
I don't know what to suggest. I don't think there's anything we can do on the AutoValue side.

**Comment by cketcham** [comment]
@eamonnmcmanus yeah I'm not sure. Just wanted to surface that extra bit of information in case it's useful.

**Comment by 3flex** [comment]
Restarting the Gradle daemon also seemed to fix this (at least temporarily) for me. Pretty annoying but at least we can work around it.

Never seen this issue on any other projects, only now while I'm hacking on auto-value-gson extension.

**Comment by davidburstromspotify** [comment]
@naturalwarren When you close Android Studio it will forcefully stop all running Gradle daemons, so essentially you had the same workaround as `./gradlew --stop`
