### ISSUE TITLE
Cannot compile with JDK 9 and AutoValue 1.2

### ISSUE THREAD

**Issue by andrewgaul** [google/auto#401]
Using JDK 9-ea+142 and AutoValue 1.2 I cannot compile Apache jclouds:

```
$ JAVA_HOME=/home/gaul/bin/jdk-9 mvn test-compile
...
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project jclouds-core: Compilation failure
[ERROR] /home/gaul/work/jclouds/core/src/test/java/org/jclouds/json/JsonTest.java:[307,20] @AutoValue processor threw an exception: com.google.auto.value.processor.escapevelocity.EvaluationException: java.lang.IllegalAccessException: class com.google.auto.value.processor.escapevelocity.ReferenceNode cannot access class com.sun.tools.javac.model.JavacTypes (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.model to unnamed module @c8f97a7
[ERROR] at com.google.auto.value.processor.escapevelocity.Node.evaluationException(Node.java:63)
[ERROR] at com.google.auto.value.processor.escapevelocity.ReferenceNode.invokeMethod(ReferenceNode.java:342)
[ERROR] at com.google.auto.value.processor.escapevelocity.ReferenceNode$MethodReferenceNode.evaluate(ReferenceNode.java:253)
[ERROR] at com.google.auto.value.processor.escapevelocity.ReferenceNode$MemberReferenceNode.evaluate(ReferenceNode.java:107)
[ERROR] at com.google.auto.value.processor.escapevelocity.Node$Cons.evaluate(Node.java:94)
[ERROR] at com.google.auto.value.processor.escapevelocity.DirectiveNode$IfNode.evaluate(DirectiveNode.java:99)
[ERROR] at com.google.auto.value.processor.escapevelocity.Node$Cons.evaluate(Node.java:94)
[ERROR] at com.google.auto.value.processor.escapevelocity.DirectiveNode$ForEachNode.evaluate(DirectiveNode.java:142)
[ERROR] at com.google.auto.value.processor.escapevelocity.Node$Cons.evaluate(Node.java:94)
[ERROR] at com.google.auto.value.processor.escapevelocity.DirectiveNode$IfNode.evaluate(DirectiveNode.java:99)
[ERROR] at com.google.auto.value.processor.escapevelocity.Node$Cons.evaluate(Node.java:94)
[ERROR] at com.google.auto.value.processor.escapevelocity.Template.evaluate(Template.java:75)
[ERROR] at com.google.auto.value.processor.TemplateVars.toText(TemplateVars.java:82)
[ERROR] at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:412)
[ERROR] at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:143)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(jdk.compiler@9-ea/JavacProcessingEnvironment.java:959)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(jdk.compiler@9-ea/JavacProcessingEnvironment.java:875)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2100(jdk.compiler@9-ea/JavacProcessingEnvironment.java:106)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(jdk.compiler@9-ea/JavacProcessingEnvironment.java:1182)
[ERROR] at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(jdk.compiler@9-ea/JavacProcessingEnvironment.java:1290)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.processAnnotations(jdk.compiler@9-ea/JavaCompiler.java:1260)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.compile(jdk.compiler@9-ea/JavaCompiler.java:939)
[ERROR] at com.sun.tools.javac.api.JavacTaskImpl$1.call(jdk.compiler@9-ea/JavacTaskImpl.java:104)
[ERROR] at com.sun.tools.javac.api.JavacTaskImpl$1.call(jdk.compiler@9-ea/JavacTaskImpl.java:100)
[ERROR] at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(jdk.compiler@9-ea/JavacTaskImpl.java:135)
[ERROR] at com.sun.tools.javac.api.JavacTaskImpl.doCall(jdk.compiler@9-ea/JavacTaskImpl.java:100)
[ERROR] at com.sun.tools.javac.api.JavacTaskImpl.call(jdk.compiler@9-ea/JavacTaskImpl.java:94)
[ERROR] at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
[ERROR] at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
[ERROR] at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:152)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-ea/Native Method)
[ERROR] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-ea/NativeMethodAccessorImpl.java:62)
[ERROR] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(java.base@9-ea/Method.java:537)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: java.lang.IllegalAccessException: class com.google.auto.value.processor.escapevelocity.ReferenceNode cannot access class com.sun.tools.javac.model.JavacTypes (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.model to unnamed module @c8f97a7
[ERROR] at jdk.internal.reflect.Reflection.throwIllegalAccessException(java.base@9-ea/Reflection.java:415)
[ERROR] at jdk.internal.reflect.Reflection.throwIllegalAccessException(java.base@9-ea/Reflection.java:406)
[ERROR] at jdk.internal.reflect.Reflection.ensureMemberAccess(java.base@9-ea/Reflection.java:111)
[ERROR] at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(java.base@9-ea/AccessibleObject.java:355)
[ERROR] at java.lang.reflect.AccessibleObject.checkAccess(java.base@9-ea/AccessibleObject.java:347)
[ERROR] at java.lang.reflect.Method.invoke(java.base@9-ea/Method.java:529)
[ERROR] at com.google.auto.value.processor.escapevelocity.ReferenceNode.invokeMethod(ReferenceNode.java:338)
[ERROR] ... 51 more
```

**Comment by eamonnmcmanus** [comment]
I'm not sure how to configure Maven with a jdk-9-ea snapshot. Since you (@andrewgaul) have presumably already done so, perhaps you can tell me how to get past this Maven problem:
[ERROR] Failed to execute goal on project auto-value: Could not resolve dependencies for project com.google.auto.value:auto-value:jar:1.4-SNAPSHOT: Could not find artifact com.sun:tools:jar:9-ea at specified path /usr/local/google/home/emcmanus/jdk-9/../lib/tools.jar -> [Help 1]

I'm pretty sure I know what the source of the AutoValue issue is, but I'd like to reproduce it properly first.

**Comment by andrewgaul** [comment]
Using this branch:

https://github.com/andrewgaul/jclouds/tree/jdk1.9

I compile with:

```
JAVA_HOME=/home/gaul/bin/jdk-9 mvn test-compile
```

Note that the `pom.xml` hard-codes the JDK 8 `rt.jar` path which you will need to update.

**Comment by eamonnmcmanus** [comment]
Sorry, your last comment is a bit gnomic. What do I need to update?

**Comment by eamonnmcmanus** [comment]
I'm also seeing a problem with a NullPointerException in the error-prone setup that is used in jcloud:

```
Caused by: java.lang.NullPointerException
	at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:157)
	at com.sun.tools.javac.file.Locations.getPathEntries(Locations.java:141)
	at com.sun.tools.javac.file.Locations.access$000(Locations.java:80)
	at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.computePath(Locations.java:649)
	at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.lazy(Locations.java:677)
	at com.sun.tools.javac.file.Locations$BootClassPathLocationHandler.isDefault(Locations.java:566)
	at com.sun.tools.javac.file.Locations.isDefaultBootClassPath(Locations.java:115)
	at com.sun.tools.javac.util.BaseFileManager.isDefaultBootClassPath(BaseFileManager.java:137)
	at com.sun.tools.javac.main.Arguments.validate(Arguments.java:411)
	at com.sun.tools.javac.main.Main.compile(Main.java:215)
	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:249)
	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:159)
	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:88)
	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
	... 28 more
```

I don't think that has anything to do with AutoValue.

**Comment by andrewgaul** [comment]
You need to use my jdk1.9 branch to disable error-prone.  You also must update the `<bootclasspath>` stanza to point to your JDK 8 `rt.jar` since this is hard-coded to `/home/gaul/`.

**Comment by eamonnmcmanus** [comment]
OK, thanks. I can reproduce the problem now.

**Comment by eamonnmcmanus** [comment]
I have been able to build your jclouds fork using this patch: https://github.com/eamonnmcmanus/auto/tree/module-patch. I needed to set auto-value.version to 1.4-SNAPSHOT too, of course. I'll send this patch for internal review at Google and it should appear in the real 1.4-SNAPSHOT soon enough.

**Comment by andrewgaul** [comment]
Verified that patch addresses my symptoms.
