### ISSUE TITLE
1.4-rc1 NPE in getFieldOfClasses

### ISSUE THREAD

**Issue by yogurtearl** [google/auto#414]
I get this compile error when using 1.4-rc1, but it works fine with 1.3.

```
 error: @AutoValue processor threw an exception: java.lang.NullPointerException
public abstract class Foo extends Bar {
                ^
        at com.google.auto.value.processor.AutoValueProcessor.getFieldOfClasses(AutoValueProcessor.java:566)
        at com.google.auto.value.processor.AutoValueProcessor.allMethodExcludedAnnotations(AutoValueProcessor.java:818)
        at com.google.auto.value.processor.AutoValueProcessor.defineVarsForType(AutoValueProcessor.java:763)
        at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:488)
        at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:195)
        at org.jetbrains.kotlin.annotation.AnnotationProcessorWrapper.process(AnnotationProcessorWrapper.kt:129)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:803)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:715)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2000(JavacProcessingEnvironment.java:93)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1023)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1130)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1141)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:832)
        at com.sun.tools.javac.main.Main.compile(Main.java:253)
        at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:214)
        at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:106)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
        at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:57)
        at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:25)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:188)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:169)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:61)```

**Comment by eamonnmcmanus** [comment]
That is surprising. The offending line is this:

```java
    TypeMirror annotationMirror =
        elementUtils.getTypeElement(annotation.getCanonicalName()).asType();
```

`annotation` is `AutoValue.CopyAnnotations.class`, so it can't be null, and neither can its `.getCanonicalName()`. `getTypeElement` could return null if the classpath didn't have `com.google.auto.value.AutoValue.CopyAnnotations`, but it's not clear to me how that could be the case. Perhaps Error Prone is invoking the compiler in some strange way, or the `org.jetbrains.kotlin.annotation` thing is interfering somehow?

**Comment by eamonnmcmanus** [comment]
Actually, I think we would see this if 1.4-rc1 is on the -processorpath but 1.3 is on the -classpath. If you ensure that the same version is in both places the problem should go away. Meanwhile we should change the code so that it behaves better in this configuration.
