### ISSUE TITLE
[AutoValue] JDK6 crash: NoClassDefFoundError: java/lang/ReflectiveOperationException

### ISSUE THREAD

**Issue by arcao** [google/auto#418]
Hi Guys,

Is AutoValue library version **1.4-rc2** still compatible with **JDK6** as is [promoted here](https://github.com/google/auto/tree/master/value)? I tried it to use with **OpenJDK6**, but it crash while compilation on:

```
An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.NoClassDefFoundError: java/lang/ReflectiveOperationException
	at com.google.auto.value.processor.escapevelocity.Parser.parseReferenceNoBrace(Parser.java:460)
	at com.google.auto.value.processor.escapevelocity.Parser.parseReference(Parser.java:448)
	at com.google.auto.value.processor.escapevelocity.Parser.parsePrimary(Parser.java:747)
	at com.google.auto.value.processor.escapevelocity.Parser.parseUnaryExpression(Parser.java:730)
	at com.google.auto.value.processor.escapevelocity.Parser.parseUnaryExpression(Parser.java:726)
	at com.google.auto.value.processor.escapevelocity.Parser.parseExpression(Parser.java:637)
	at com.google.auto.value.processor.escapevelocity.Parser.parseIfOrElseIf(Parser.java:280)
	at com.google.auto.value.processor.escapevelocity.Parser.parseDirective(Parser.java:249)
	at com.google.auto.value.processor.escapevelocity.Parser.parseNode(Parser.java:190)
	at com.google.auto.value.processor.escapevelocity.Parser.parse(Parser.java:124)
	at com.google.auto.value.processor.escapevelocity.Template.parseFrom(Template.java:56)
	at com.google.auto.value.processor.TemplateVars.templateFromInputStream(TemplateVars.java:138)
	at com.google.auto.value.processor.TemplateVars.parsedTemplateForResource(TemplateVars.java:112)
	at com.google.auto.value.processor.AutoValueTemplateVars.<clinit>(AutoValueTemplateVars.java:192)
	at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:478)
	at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:195)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:735)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:664)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:809)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1061)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:796)
	at com.sun.tools.javac.main.Main.compile(Main.java:388)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:133)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:171)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: java.lang.ReflectiveOperationException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	... 48 more
```

The issue is in **ReferenceNode** class where [is used ReflectiveOperationException](https://github.com/google/auto/search?utf8=%E2%9C%93&q=ReflectiveOperationException) which is **introduced in Java 1.7**.

**Comment by eamonnmcmanus** [comment]
Interesting! This isn't deliberate, since we have had a policy up until now of allowing AutoValue to function on Java 6. However, the Travis CI set up for this project only tests Java 7, so apparently we've lapsed.

We are planning that we may drop support after 1.4 for compiling *on* Java 7 (and *a fortiori* Java 6). We still intend to support compiling *for* Java 6, with `-source 6 -target 6 -bootclasspath <rt.jar from 6>`. If you have a reason to want to compile *on* earlier versions we'd be very interested to know what it is. Meanwhile, fixing support for Java 6 may not be our highest priority.

**Comment by ekuefler** [comment]
If you do choose to continue supporting it, the fix at least for this case is trivial - I just sent a pull request. I haven't checked whether there are other Java6 incompatibilities, though.

**Comment by eamonnmcmanus** [comment]
Yes, of course. I have checked that this is the only Java 6 incompatibility we have, and I think the simplest fix is just to catch Exception rather than ReflectiveOperationException.
