### ISSUE TITLE
Auto-Factory beta4 wails with DuplicateFileException

### ISSUE THREAD

**Issue by PaulWoitaschek** [google/auto#474]
When I have a very minimal setup with a factory like:

```java
public class MainActivity extends AppCompatActivity {

  @Inject MainActivity_DependencyFactory dependencyFactory;

  @Component(modules = MyModule.class)
  public interface MyComponent {}

  @AutoFactory public static class Dependency {

    public Dependency(@Provided String string) {}
  }

  @Module public abstract class MyModule {

    @Provides String provideString() {
      return "something";
    }
  }
}
```

With only the necessary dependencies

```groovy

dependencies {
    compile 'com.android.support:appcompat-v7:25.3.1'
    provided "javax.annotation:jsr250-api:1.0"

    compile 'com.google.dagger:dagger:2.10'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.10'

    compile "com.google.auto.factory:auto-factory:1.0-beta4"
    compile 'com.android.support:multidex:1.0.1'
}
```

It works fine with beta3. However with beta4 I get a lot errors. I already cleared the cache.

```
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK plugin.xml
  	File1: /home/ph1b/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.contenttype/3.4.100/7052e115041d04410a4519a61307502fb7c138e6/org.eclipse.core.contenttype-3.4.100.jar
  	File2: /home/ph1b/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/org.eclipse.equinox.app/1.3.100/e7169b33d352f5ddb6eace73f5a4d29aae3b91ec/org.eclipse.equinox.app-1.3.100.jar
  	File3: /home/ph1b/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.filesystem/1.3.100/37fce4f5488a21ce36021d4909acaf5687e1595e/org.eclipse.core.filesystem-1.3.100.jar
  	File4: /home/ph1b/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/org.eclipse.equinox.registry/3.5.101/eac5aeb82732847bc7f11e2b5c934004c4c7a543/org.eclipse.equinox.registry-3.5.101.jar
  	File5: /home/ph1b/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/org.eclipse.equinox.preferences/3.4.1/6770649a91266a4a17747b201723a1fea8c8a198/org.eclipse.equinox.preferences-3.4.1.jar
  	File6: /home/ph1b/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.expressions/3.4.300/42b2139abd5638730db317a51949dac3b8d81492/org.eclipse.core.expressions-3.4.300.jar
  	File7: /home/ph1b/.gradle/caches/modules-2/files-2.1/org.eclipse.jdt/org.eclipse.jdt.core/3.10.0/647e19b28c106a63a14401c0f5956289792adf2f/org.eclipse.jdt.core-3.10.0.jar
  	File8: /home/ph1b/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.resources/3.7.100/6c56ea28b84afe7d55de02763846e76dbfb0b689/org.eclipse.core.resources-3.7.100.jar
  	File9: /home/ph1b/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.runtime/3.7.0/6658c235056134f7e86295e751129508802d71f2/org.eclipse.core.runtime-3.7.0.jar
```

**Comment by LegendaryZ** [comment]
I'm having the same problem
```
* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK plugin.xml
	File1: C:\Users\Jason\.gradle\caches\modules-2\files-2.1\org.eclipse.core\org.eclipse.core.runtime\3.7.0\6658c235056134f7e86295e751129508802d71f2\org.eclipse.core.runtime-3.7.0.jar
	File2: C:\Users\Jason\.gradle\caches\modules-2\files-2.1\org.eclipse.core\org.eclipse.core.filesystem\1.3.100\37fce4f5488a21ce36021d4909acaf5687e1595e\org.eclipse.core.filesystem-1.3.100.jar
	File3: C:\Users\Jason\.gradle\caches\modules-2\files-2.1\org.eclipse.core\org.eclipse.core.expressions\3.4.300\42b2139abd5638730db317a51949dac3b8d81492\org.eclipse.core.expressions-3.4.300.jar
	File4: C:\Users\Jason\.gradle\caches\modules-2\files-2.1\org.eclipse.core\org.eclipse.core.contenttype\3.4.100\7052e115041d04410a4519a61307502fb7c138e6\org.eclipse.core.contenttype-3.4.100.jar
	File5: C:\Users\Jason\.gradle\caches\modules-2\files-2.1\org.eclipse.jdt\org.eclipse.jdt.core\3.10.0\647e19b28c106a63a14401c0f5956289792adf2f\org.eclipse.jdt.core-3.10.0.jar
	File6: C:\Users\Jason\.gradle\caches\modules-2\files-2.1\org.eclipse.equinox\org.eclipse.equinox.app\1.3.100\e7169b33d352f5ddb6eace73f5a4d29aae3b91ec\org.eclipse.equinox.app-1.3.100.jar
	File7: C:\Users\Jason\.gradle\caches\modules-2\files-2.1\org.eclipse.equinox\org.eclipse.equinox.registry\3.5.101\eac5aeb82732847bc7f11e2b5c934004c4c7a543\org.eclipse.equinox.registry-3.5.101.jar
	File8: C:\Users\Jason\.gradle\caches\modules-2\files-2.1\org.eclipse.equinox\org.eclipse.equinox.preferences\3.4.1\6770649a91266a4a17747b201723a1fea8c8a198\org.eclipse.equinox.preferences-3.4.1.jar
	File9: C:\Users\Jason\.gradle\caches\modules-2\files-2.1\org.eclipse.core\org.eclipse.core.resources\3.7.100\6c56ea28b84afe7d55de02763846e76dbfb0b689\org.eclipse.core.resources-3.7.100.jar

```
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:support-annotations:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    testCompile 'junit:junit:4.12'
    // RxJava
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.1.6'
    compile 'com.jakewharton.rxrelay:rxrelay:1.2.0'
    // Dagger2
    compile 'com.google.dagger:dagger:2.10'
    apt 'com.google.dagger:dagger-compiler:2.10'
    // Autovalue
    compile 'com.google.auto.value:auto-value:1.4.1'
    apt "com.google.auto.value:auto-value:1.4.1"
    // Autofactory
    compile 'com.google.auto.factory:auto-factory:1.0-beta4'
    compile 'com.ryanharter.auto.value:auto-value-parcel-adapter:0.2.5'
    // https://android-arsenal.com/details/1/3433
    // When using AutoValue with Gradle it is highly inconvenient to specify the dependency both as apt and provided.
    // Doing so leaks all of AutoValue's annotation processor code and its shaded dependencies into your classpath.
    // This project allows you to only depend on the annotations as provided and specify the processor only as an apt dependency.
    provided 'com.jakewharton.auto.value:auto-value-annotations:1.2-update1'
    apt 'com.ryanharter.auto.value:auto-value-gson:0.4.5'
    provided 'com.ryanharter.auto.value:auto-value-gson:0.4.5'
    compile "com.google.code.gson:gson:2.8.0"
    compile 'com.jakewharton:butterknife:8.4.0'
    apt 'com.jakewharton:butterknife-compiler:8.4.0'

    debugCompile 'com.facebook.stetho:stetho:1.4.1'
    debugCompile 'com.uphyca:stetho_realm:2.0.0'
}

```

**Comment by ronshapiro** [comment]
None of this appears to look like AutoFactory... What is the last version that did work for you?

**Comment by PaulWoitaschek** [comment]
Beta3 compiles. It's really an empty project with the factory as the sole dependency.

**Comment by JakeWharton** [comment]
Auto factory shouldn't be a compile dep

**Comment by PaulWoitaschek** [comment]
And what should it be instead? Would be great to have some instructions in the readme, I don't like to put jars in my project .

**Comment by JakeWharton** [comment]
It's an annotation processor so it should be annotationProcessor. The
annotations are tragically bundled just like all the auto libraries so you
either need to copy them into your project or also add a provided dep as
well.

**Comment by PaulWoitaschek** [comment]
Thanks, it would be great if that was mentioned in the wiki. It just speaks about adding a jar.

In java it seems to work but when I'm using kotlin it fails:

```kotlin
class MainActivity : AppCompatActivity() {

  @Inject lateinit var dependencyFactory: MainActivity_DependencyFactory

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    DaggerMainActivity_MyComponent.create()
        .inject(this)
  }

  @Component(modules = arrayOf(MyModule::class))
  interface MyComponent {
    fun inject(target: MainActivity)
  }

  @AutoFactory class Dependency(@Provided provided: String, necessary: String)

  @Module class MyModule {

    @Provides internal fun provideString(): String {
      return "something"
    }
  }
}
```

It just fails to build with
```
e: /home/ph1b/Dev/BrokenDaggerAutoFactory/app/build/tmp/kapt3/stubs/debug/de/paul_woitaschek/brokendaggerautofactory/MainActivity.java:29: error: error.NonExistentClass cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method.
e: 

e:         public abstract void inject(@org.jetbrains.annotations.NotNull()
e:                              ^
e:       error.NonExistentClass is injected at
e:           de.paul_woitaschek.brokendaggerautofactory.MainActivity.dependencyFactory
e:       de.paul_woitaschek.brokendaggerautofactory.MainActivity is injected at
e:           de.paul_woitaschek.brokendaggerautofactory.MainActivity.MyComponent.inject(p0)
e: /home/ph1b/Dev/BrokenDaggerAutoFactory/app/src/main/java/de/paul_woitaschek/brokendaggerautofactory/MainActivity.kt: (1, 1): Some error(s) occurred while processing annotations. Please see the error messages above.
e: /home/ph1b/Dev/BrokenDaggerAutoFactory/app/src/main/java/de/paul_woitaschek/brokendaggerautofactory/MainActivity.kt: (19, 43): Unresolved reference: MainActivity_DependencyFactory
```

This is how I setup my dependencies:

```
dependencies {
    provided "javax.annotation:jsr250-api:1.0"

    compile 'com.google.dagger:dagger:2.10'
    kapt 'com.google.dagger:dagger-compiler:2.10'

    kapt "com.google.auto.factory:auto-factory:1.0-beta4"
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
}
```

**Comment by Philipp91** [comment]
> It's an annotation processor so it should be annotationProcessor. The annotations are tragically bundled just like all the auto libraries so you either need to copy them into your project or also add a provided dep as well.

I get the same error with `compile 'com.google.auto.factory:auto-factory:1.0-beta4'`. When I use `annotationProcessor 'com.google.auto.factory:auto-factory:1.0-beta4'`, it can't find the `@AutoFactory` annotation and the build fails. When I add `provided 'com.google.auto.factory:auto-factory:1.0-beta4'`, it compiles fine but I get a runtime error 

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/auto/factory/internal/Preconditions;
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.auto.factory.internal.Preconditions" on path: DexPathList[[...]]
                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                  	... 33 more
```

So yes, it would be great if the readme could explain how to use auto-factory with Gradle correctly.

**Comment by eamonnmcmanus** [comment]
@ronshapiro the runtime dependency on Preconditions has been removed, hasn't it? Perhaps we should make another release without it?

**Comment by ronshapiro** [comment]
It was rolled back and I haven't had time to look at why yet

**Comment by ronshapiro** [comment]
The runtime dependency is removed in `1.0-beta5` (just released

**Comment by Sydney-o9** [comment]
I had to downgrade to `1.0-beta2`.

````
    compile 'com.google.auto.factory:auto-factory:1.0-beta2'
````

I get the following errors with `1.0-beta5':

````
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK plugin.xml
  	File1: /Users/miaou/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/org.eclipse.equinox.app/1.3.100/e7169b33d352f5ddb6eace73f5a4d29aae3b91ec/org.eclipse.equinox.app-1.3.100.jar
  	File2: /Users/miaou/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.resources/3.7.100/6c56ea28b84afe7d55de02763846e76dbfb0b689/org.eclipse.core.resources-3.7.100.jar
  	File3: /Users/miaou/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/org.eclipse.equinox.preferences/3.4.1/6770649a91266a4a17747b201723a1fea8c8a198/org.eclipse.equinox.preferences-3.4.1.jar
  	File4: /Users/miaou/.gradle/caches/modules-2/files-2.1/org.eclipse.equinox/org.eclipse.equinox.registry/3.5.101/eac5aeb82732847bc7f11e2b5c934004c4c7a543/org.eclipse.equinox.registry-3.5.101.jar
  	File5: /Users/miaou/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.filesystem/1.3.100/37fce4f5488a21ce36021d4909acaf5687e1595e/org.eclipse.core.filesystem-1.3.100.jar
  	File6: /Users/miaou/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.expressions/3.4.300/42b2139abd5638730db317a51949dac3b8d81492/org.eclipse.core.expressions-3.4.300.jar
  	File7: /Users/miaou/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.runtime/3.7.0/6658c235056134f7e86295e751129508802d71f2/org.eclipse.core.runtime-3.7.0.jar
  	File8: /Users/miaou/.gradle/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.contenttype/3.4.100/7052e115041d04410a4519a61307502fb7c138e6/org.eclipse.core.contenttype-3.4.100.jar
  	File9: /Users/miaou/.gradle/caches/modules-2/files-2.1/org.eclipse.jdt/org.eclipse.jdt.core/3.10.0/647e19b28c106a63a14401c0f5956289792adf2f/org.eclipse.jdt.core-3.10.0.jar
````

**Comment by ronshapiro** [comment]
Ah. We can probably fix this by upgrading the version of GoogleJavaFormat

**Comment by jhass** [comment]
```gradle
provided 'com.google.auto.factory:auto-factory:1.0-beta5'
annotationProcessor 'com.google.auto.factory:auto-factory:1.0-beta5'
```

works for me,  +1 to mentioning this in the readme.

**Comment by filipkowicz** [comment]
take a look at: https://kotlinlang.org/docs/reference/kapt.html#non-existent-type-correction

adding that:
```
    kapt {
        correctErrorTypes = true
    }
``` fixed problem
also remember to exclude guava if you don use. Anyway it would be great if you provide annotations only package
```compileOnly("com.google.auto.factory:auto-factory:1.0-beta5") {
        exclude(group: 'com.google.guava')
    }```
