### ISSUE TITLE
Breakage on Java 9 and Eclipse Oxygen

### ISSUE THREAD

**Issue by davido** [google/auto#645]
//CC @cushon.

I'm trying to set Gerrit Code Review up and running on Java 9 in Eclipse-Oxygen and seeing this Exception on this code: https://github.com/GerritCodeReview/gerrit/blob/master/java/com/google/gerrit/sshd/Commands.java#L46-L50

```
@AutoAnnotation processor threw an exception: java.lang.IllegalArgumentException: Field cannot be null (was it set?): java.lang.String com.google.auto.value.processor.AutoAnnotationTemplateVars.generated
	at com.google.auto.value.processor.TemplateVars.toVars(TemplateVars.java:100)
	at com.google.auto.value.processor.TemplateVars.toText(TemplateVars.java:91)
	at com.google.auto.value.processor.AutoAnnotationProcessor.processMethod(AutoAnnotationProcessor.java:175)
	at com.google.auto.value.processor.AutoAnnotationProcessor.process(AutoAnnotationProcessor.java:128)
	at com.google.auto.value.processor.AutoAnnotationProcessor.process(AutoAnnotationProcessor.java:111)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:933)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:443)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:419)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:372)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:187)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:305)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:403)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:566)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:544)
	at org.eclipse.core.internal.resources.Project.build(Project.java:112)
	at org.eclipse.jdt.internal.ui.util.CoreUtility$BuildJob.run(CoreUtility.java:159)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

To reproduce, build Bazel from HEAD (eb587075b0d6ffab1cf9e69ede1b7e547905e547), clone [Gerrit Code Review](https://gerrit.googlesource.com/gerrit) from HEAD (59c8e6bab1f09e4590cacb490c46ea36cfc9f9fc) and apply this CL: [1]. Then run:

```
  $ tools/eclipse/project.py --java9
```

to generate [.classpath](http://paste.openstack.org/show/724263/) file and open Eclipse Oxygen and try to build Gerrit ptoject.

Used Eclipse version:

```
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
```

[1] https://gerrit-review.googlesource.com/c/gerrit/+/186491

**Comment by cushon** [comment]
@davido I think #646 (specifically 32a0ae3bf1a37be063cc3bdf9d599f38a1716db4) will fix this.

**Comment by davido** [comment]
@cushon Thank you! That fixed it indeed. Can we upstream that patch and conduct a new auto-value release?

**Comment by eamonnmcmanus** [comment]
The 1.6.2 release contains this fix.

**Comment by davido** [comment]
@eamonnmcmanus Thank you! I've uploaded the auto-value upgrade upstream: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/186872
