### ISSUE TITLE
ClassCastException in AutoServiceProcessor

### ISSUE THREAD

**Issue by shevek** [google/auto#665]
```
error: FATAL ERROR: java.lang.ClassCastException: java.lang.String cannot be cast to javax.lang.model.type.DeclaredType
        at com.google.auto.service.processor.AutoServiceProcessor.getProviderInterface(AutoServiceProcessor.java:264)
        at com.google.auto.service.processor.AutoServiceProcessor.processAnnotations(AutoServiceProcessor.java:133)
        at com.google.auto.service.processor.AutoServiceProcessor.processImpl(AutoServiceProcessor.java:115)
        at com.google.auto.service.processor.AutoServiceProcessor.process(AutoServiceProcessor.java:101)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
```

While I know the code I'm compiling contains a compile error, I don't think AutoService should CCE. I was actually compiling to find the compile error. I'm sorry I don't have a self-contained test case, but I hope this stack trace is enough for you to know that javac might hand you a String at that location, and silently ignore it if so.

My guess is that I used `@AutoService(Foo.class)` where `Foo` wasn't imported - although I did this a hundred times, due to renaming Foo. I'm not sure why one in particular caused a CCE.

**Comment by shevek** [comment]
javac 1.8.0_181
gradle 4.5.1
Ubuntu 16.04.5 LTS
Nothing special.

**Comment by tbroyer** [comment]
Looks like you may not be using 1.0-rc-4 actually; there's no `getProviderInterface` method in rc-4:
https://github.com/google/auto/blob/auto-service-1.0-rc4/service/src/main/java/com/google/auto/service/processor/AutoServiceProcessor.java#264
You might be using rc-3 or earlier, but that `getProviderInterface` method was removed in December 2017 (in https://github.com/google/auto/commit/c02f8396f410b6f89872bd23e2adb50e0832528a, authored in August but not pushed/committed until December), and rc-3 was released in February 2017 (https://search.maven.org/search?q=g:com.google.auto.service%20AND%20a:auto-service&core=gav)
