### ISSUE TITLE
AutoFactory does not compile with AndroidX and android.enableJetifier

### ISSUE THREAD

**Issue by nkotula** [google/auto#668]
## Description

We're trying to migrate our project to AndroidX, but one of AutoFactory's dependencies cannot be transformed using the Jetifier, thus the entire build fails.  We're pretty sure it's this particular library because we are able to reproduce the build failure in a new project with the only extra dependency being AutoFactory.

It appears that the `org.eclipse.jdt.core-3.10.0` dependency within AutoFactory is causing the issue.

## Relevant system info

* Android Studio 3.2
* Build #AI-181.5540.7.32.5014246, built on September 17, 2018
* Gradle version 4.6
* Gradle Plugin version 3.2.0
* JRE: 1.8.0_152-release-1136-b06 x86_64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* macOS 10.13.6

## Steps to reproduce:

1. Start a new Android Studio project with these settings:
   1. Include Kotlin Support
   1. Phone and Tablet form factors
   1. Minimum API level = 16
   1. Start with Empty Activity
   1. Enable AppCompat
1. Use the AndroidX refactor tool to convert the project to AndroidX (and verify that everything still runs)
1. Add `implementation 'com.google.auto.factory:auto-factory:1.0-beta5'` as a dependency
1. Rebuilding the project fails with the following stack trace:

```
12:43:56.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:43:56.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:43:56.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:43:56.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
12:43:56.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not resolve all files for configuration ':app:debugCompileClasspath'.
12:43:56.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to transform file 'org.eclipse.jdt.core-3.10.0.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
12:43:56.333 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > Failed to transform '/Users/nkotula/.gradle/caches/modules-2/files-2.1/org.eclipse.jdt/org.eclipse.jdt.core/3.10.0/647e19b28c106a63a14401c0f5956289792adf2f/org.eclipse.jdt.core-3.10.0.jar' using Jetifier. Reason: The type does not support '.' as package separator! Received 'java.lang.Object;Ljava.lang.Class'.. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file.
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugCompileClasspath'.
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:944)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1600(DefaultConfiguration.java:120)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:918)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(AbstractFileCollectionSnapshotter.java:72)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:234)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:185)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:55)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.state.DefaultCompileClasspathSnapshotter.snapshot(DefaultCompileClasspathSnapshotter.java:38)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.snapshotTaskFiles(CacheBackedTaskHistoryRepository.java:329)
12:43:56.334 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.createExecution(CacheBackedTaskHistoryRepository.java:151)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.access$100(CacheBackedTaskHistoryRepository.java:61)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$1.getCurrentExecution(CacheBackedTaskHistoryRepository.java:111)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:208)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:93)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:50)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
12:43:56.335 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.lang.Thread.run(Thread.java:745)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.artifacts.transform.ArtifactTransformException: Failed to transform file 'org.eclipse.jdt.core-3.10.0.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.UserCodeBackedTransformer.transform(UserCodeBackedTransformer.java:89)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.ChainedTransformer.transform(ChainedTransformer.java:36)
12:43:56.336 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.TransformArtifactOperation.run(TransformArtifactOperation.java:41)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.access$900(DefaultBuildOperationExecutor.java:63)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor$ParentPreservingQueueWorker.execute(DefaultBuildOperationExecutor.java:378)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:230)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.access$600(DefaultBuildOperationQueue.java:172)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:209)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable$1.call(DefaultBuildOperationQueue.java:203)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:202)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:177)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 6 more
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: Failed to transform '/Users/nkotula/.gradle/caches/modules-2/files-2.1/org.eclipse.jdt/org.eclipse.jdt.core/3.10.0/647e19b28c106a63a14401c0f5956289792adf2f/org.eclipse.jdt.core-3.10.0.jar' using Jetifier. Reason: The type does not support '.' as package separator! Received 'java.lang.Object;Ljava.lang.Class'.. (Run with --stacktrace for more details.) To disable Jetifier, set android.enableJetifier=false in your gradle.properties file.
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.internal.dependency.JetifyTransform.transform(JetifyTransform.kt:204)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:44)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.TransformArtifactsAction.apply(TransformArtifactsAction.java:29)
12:43:56.337 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:224)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$TransformAction.execute(DefaultTransformedFileCache.java:211)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:111)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore$1.execute(DefaultPathKeyFileStore.java:107)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.doAdd(DefaultPathKeyFileStore.java:160)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:107)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.resource.local.DefaultPathKeyFileStore.add(DefaultPathKeyFileStore.java:50)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:143)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1$1.create(DefaultTransformedFileCache.java:122)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.withFileLock(LockOnDemandCrossProcessCacheAccess.java:89)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultCacheAccess.withFileLock(DefaultCacheAccess.java:193)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.withFileLock(DefaultPersistentDirectoryStore.java:158)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.withFileLock(DefaultCacheFactory.java:187)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:122)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache$1.create(DefaultTransformedFileCache.java:115)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.ProducerGuard$AdaptiveProducerGuard.guardByKey(ProducerGuard.java:97)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.loadIntoCache(DefaultTransformedFileCache.java:115)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.DefaultTransformedFileCache.getResult(DefaultTransformedFileCache.java:107)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.artifacts.transform.UserCodeBackedTransformer.transform(UserCodeBackedTransformer.java:87)
12:43:56.338 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 20 more
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException: The type does not support '.' as package separator! Received 'java.lang.Object;Ljava.lang.Class'.
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.tools.build.jetifier.core.type.JavaType.<init>(JavaType.kt:28)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.tools.build.jetifier.processor.transform.bytecode.asm.CustomRemapper.mapValue(CustomRemapper.kt:49)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.commons.MethodRemapper.visitLdcInsn(MethodRemapper.java:179)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1582)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.tools.build.jetifier.processor.transform.bytecode.ByteCodeTransformer.runTransform(ByteCodeTransformer.kt:39)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:328)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.tools.build.jetifier.processor.archive.ArchiveFile.accept(ArchiveFile.kt:41)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:316)
12:43:56.339 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.tools.build.jetifier.processor.archive.Archive.accept(Archive.kt:66)
12:43:56.340 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.tools.build.jetifier.processor.Processor.transformLibrary(Processor.kt:312)
12:43:56.340 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.tools.build.jetifier.processor.Processor.transform(Processor.kt:175)
12:43:56.340 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at com.android.build.gradle.internal.dependency.JetifyTransform.transform(JetifyTransform.kt:199)
12:43:56.340 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 41 more
12:43:56.340 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:43:56.340 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
12:43:56.340 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
12:43:56.340 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
12:43:56.340 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1s
```

**Comment by JakeWharton** [comment]
This is not AutoFactory's problem unless you're advocating for them to not use google-java-format (which I _strongly_ support). In any case it's already filed against Jetifier: https://issuetracker.google.com/issues/113224601

**Comment by nkotula** [comment]
@JakeWharton Thanks for pointing me to that issue.  I think it'd be great for AutoFactory to not need that dependency, but that's a larger issue.  This can be closed I guess.

**Comment by tbroyer** [comment]
Try using:
```gradle
implementation 'com.google.auto.factory:auto-factory:1.0-beta5@jar'
annotationProcessor 'com.google.auto.factory:auto-factory:1.0-beta5'
```

You could also use
```gradle
implementation('com.google.auto.factory:auto-factory:1.0-beta5') { transitive = false }
```
instead of the `@jar` notation.
